learning_templates/basic_app/urls.py
from django.conf.urls import url
from basic_app import views



app_name = 'basic_app'

urlpatterns = [
    url(r'^relative/$',views.relative,name='relative'),
    url(r'^other/$',views.other,name='other'),
]

learning_templates/learning_templates/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from basic_app import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^basic_app/',include('basic_app.urls')),
]

learning_templates/basic_app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf.urls import url
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'hello world','number':100}
    return render(request,'basic_app/index.html',context_dict)

def other(request):
    return render(request,'basic_app/other.html')

def relative(request):
    return render(request,'basic_app/relative_url.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title></title>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">


</head>
<body>
	<nav class="navbar navbar-default navbar-static-top">
	<div class="container">
		<ul class="nav navbar-nav">
		<li><a class="navbar-brand"><a href="{% url 'index'%}">BRAND</a></li>
		<li><a class="navbar-link"><a href="{% url 'admin:index'%}">Admin</a></li>
		<li><a class="navbar-link"><a href="{% url 'basic_app:other'%}">Other</a></li>
		<li><a class="navbar-link"><a href="{% url 'basic_app:relative'%}">Relative</a></li>
		
		</ul>
	</div>
	</nav>
	<div class = "container">
	{% block body_block %}


	{% endblock %}



</body>


</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html"%}
{%load my_extras%}
	{% block body_block%}
<h1>Welcome to index</h1>
<h2>this is index.html showing</h2>
	<h1>{{text|cut:'hello'}}</h1>
	<h1>{{number|add:"99"}}</h1>
	{% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html"%}
	{% block body_block %}
<h1>Welcome to other</h1>
<h2>this is an example of template inheritance</h2>
	{% endblock %}

learning_templates/templates/basic_app/relative_url.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
</head>
<body>
<h1>Welcome to relative url templates</h1>
<a href="{% url 'basic_app:other' %}">The other page</a>


</body>


</html>